#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:~/test
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2
camunda.bpm.admin-user:
  id: demo
  password: demo


